# Auspex Dataset Construction

## Objective

Create a clean training dataset for Auspex using the raw CIC-Bell-DNS2021 domain lists.

The final dataset will contain:

- domain
- label

where label is one of:

- benign
- phishing
- malware
- spam

This dataset will be used for feature engineering and model training.

## Why We Chose the Raw Dataset

The CIC-Bell-DNS2021 processed CSVs contain engineered DNS features and parsing inconsistencies.

The raw domain lists:

- are cleaner
- directly match user input
- are easier to explain
- allow us to generate our own features

# Auspex Dataset Construction

## Objective

Create a clean training dataset from the CIC-Bell-DNS2021 raw domain lists.

Final schema:

| domain | label |
|---------|---------|
| google.com | benign |
| evil-login.net | phishing |

Labels:
- benign
- phishing
- malware
- spam

This dataset will be used for feature engineering and model training.

In [1]:
import pandas as pd
from urllib.parse import urlparse

In [2]:
benign = pd.read_csv(
    "../data/raw/cic_bell_dns2021_raw/benign_domains.csv",
    header=None,
    names=["domain"]
)

malware = pd.read_csv(
    "../data/raw/cic_bell_dns2021_raw/malware_domains.csv",
    header=None,
    names=["domain"]
)

spam = pd.read_csv(
    "../data/raw/cic_bell_dns2021_raw/spam_domains.csv",
    header=None,
    names=["domain"]
)

print("Benign:", benign.shape)
print("Malware:", malware.shape)
print("Spam:", spam.shape)

Benign: (988667, 1)
Malware: (26894, 1)
Spam: (8254, 1)

In [3]:
phishing_raw = pd.read_csv(
    "../data/raw/cic_bell_dns2021_raw/phishing_domains.csv",
    header=None
)

print(phishing_raw.shape)

phishing_raw.head()

(16307, 33)

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,6086873,http://programafidelidadeitacard2.cf/,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:56:11+00:00,yes,2019-06-20T13:03:42+00:00,yes,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6086871,http://professorjosesilveira.com/wp-content/th...,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:56:02+00:00,yes,2019-06-20T13:03:01+00:00,yes,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6086867,http://revcaint.com/directing/www.cibc.mobi/ac...,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:50+00:00,yes,2019-06-20T13:01:38+00:00,yes,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6086866,http://www.ksylitol.com/dioau/ourtimelogin/v3/,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:46+00:00,yes,2019-06-20T13:00:57+00:00,yes,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6086865,http://www.ksylitol.com/jiwo/ourtimelogin/v3/,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:42+00:00,yes,2019-06-20T13:00:15+00:00,yes,Other,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
phishing_raw.iloc[:10, :5]

,0,1,2,3,4
0,6086873,http://programafidelidadeitacard2.cf/,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:56:11+00:00,yes
1,6086871,http://professorjosesilveira.com/wp-content/th...,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:56:02+00:00,yes
2,6086867,http://revcaint.com/directing/www.cibc.mobi/ac...,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:50+00:00,yes
3,6086866,http://www.ksylitol.com/dioau/ourtimelogin/v3/,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:46+00:00,yes
4,6086865,http://www.ksylitol.com/jiwo/ourtimelogin/v3/,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:42+00:00,yes
5,6086864,http://139.59.55.98/banks/Simplii/,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:38+00:00,yes
6,6086863,http://139.59.55.98/banks/Simplii,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:37+00:00,yes
7,6086862,https://a1professionals.net/vendor/firebase/ph...,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:33+00:00,yes
8,6086861,http://www.sauveurgasparine.com/fr/modules/blo...,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:55:29+00:00,yes
9,6086855,https://services.runescape.com-ex.ru/m=weblogi...,http://www.phishtank.com/phish_detail.php?phis...,2019-06-20T12:49:39+00:00,yes

In [5]:
def extract_domain(url):
    try:
        return urlparse(url).netloc.lower()
    except:
        return None

In [6]:
phishing = pd.DataFrame()

phishing["domain"] = phishing_raw[1].apply(extract_domain)

phishing.head()

                          domain
0  programafidelidadeitacard2.cf
1      professorjosesilveira.com
2                   revcaint.com
3               www.ksylitol.com
4               www.ksylitol.com

In [7]:
benign["label"] = "benign"
malware["label"] = "malware"
spam["label"] = "spam"
phishing["label"] = "phishing"

In [8]:
combined = pd.concat(
    [
        benign,
        phishing,
        malware,
        spam
    ],
    ignore_index=True
)

print(combined.shape)
combined.head()

(1040122, 2)

               domain   label
0         cypress.com  benign
1              boy.jp  benign
2              nnm.ru  benign
3  1stwebdesigner.com  benign
4        ordasoft.com  benign

In [9]:
combined = combined.dropna()

combined["domain"] = combined["domain"].str.strip()

combined = combined.drop_duplicates()

print(combined.shape)

(1025473, 2)

In [10]:
combined["label"].value_counts()

label
benign      988667
malware      26894
phishing      9076
spam           836
Name: count, dtype: int64

In [11]:
combined.sample(20)

                           domain     label
635595                   hfpg.org    benign
984611                yiliu88.com    benign
444058   thewhitehouseproject.org    benign
383155            discoveryvr.com    benign
993346  s1.node103.iifab.com:3333  phishing
778101     blueprintfurniture.com    benign
124996                  bva.co.uk    benign
62910              girleffect.org    benign
7894             xiamenair.com.cn    benign
178699                 sohowz.com    benign
899562                clasohm.com    benign
572804              fomaxtech.com    benign
565487            youyanglife.com    benign
946524           coleggwent.ac.uk    benign
883125                  belch.com    benign
159215              fortynine.com    benign
660356            jlorcompany.com    benign
368929                sacp.org.za    benign
186298               thru-you.com    benign
748222                  unique.dk    benign

In [12]:
combined["domain"].nunique()

1025005

In [13]:
combined["domain"].nunique()

1025005

In [14]:
combined.groupby("domain")["label"].nunique().sort_values(ascending=False)

domain
samanthaanayaphotography.com    3
777foryou.com                   2
ablerefrigeration.com           2
jikimger.pw                     2
icontextil.com.br               2
                               ..
zzzezeroe.fr                    1
zzzfgjj.com                     1
zzzgc.net                       1
zzzhhg.com                      1
zzzzdreams.com                  1
Name: label, Length: 1025005, dtype: int64

In [15]:
conflicts = combined.groupby("domain")["label"].nunique()

conflicts = conflicts[conflicts > 1]

print(len(conflicts))

467

In [16]:
conflicting_domains = conflicts.index

combined[
    combined["domain"].isin(conflicting_domains)
].sort_values("domain")

                        domain     label
1002903     100000munkahely.hu  phishing
1020463     100000munkahely.hu   malware
996451                  163.lu  phishing
332558                  163.lu    benign
1006179              191gm.com   malware
...                        ...       ...
714762   zilmaraalencar.com.br    benign
1002161          zipansion.com  phishing
40074            zipansion.com    benign
989996            zmievski.org  phishing
423598            zmievski.org    benign

[935 rows x 2 columns]

Domains with conflicting labels were removed.

Reason:
The same domain occasionally appeared under multiple labels
(e.g. benign and phishing).

To reduce label ambiguity, all conflicting domains were excluded
from the final training dataset.

In [17]:
conflicts = (
    combined.groupby("domain")["label"]
    .nunique()
)

bad_domains = conflicts[
    conflicts > 1
].index

cleaned = combined[
    ~combined["domain"].isin(bad_domains)
]

In [18]:
cleaned.shape

(1024538, 2)

In [19]:
print(cleaned.shape)

cleaned.to_csv(
    "../data/processed/auspex_domains_v1.csv",
    index=False
)

print("Saved auspex_domains_v1.csv")

(1024538, 2)
Saved auspex_domains_v1.csv

In [20]:
print(cleaned.shape)

(1024538, 2)

In [21]:
cleaned["label"].value_counts()

label
benign      988299
malware      26703
phishing      8705
spam           831
Name: count, dtype: int64

In [22]:
cleaned.sample(20)

                         domain    label
40871       bikulikaoquanyu.com   benign
477335          malariasite.com   benign
717560         jodeemessina.com   benign
602092                37125.com   benign
1016889  rrforeverjewellery.com  malware
722473            peoplecars.ro   benign
249847              mukovoz.com   benign
267049        mundoprimaria.com   benign
473429               megaman.cc   benign
586425            surfpoeten.de   benign
854968         sugarcrafter.net   benign
305218               kakupb.com   benign
94897     uverserouterlogin.com   benign
705493        florinhasdarua.pt   benign
148818    itil-officialsite.com   benign
255908        tickletheater.com   benign
642172          fajr-jeddah.org   benign
42232                 yigay.com   benign
319451               flyvlm.com   benign
794004              skylook.org   benign

## Result

Created:

auspex_domains_v1.csv

Schema:

- domain
- label

This dataset serves as the foundation for Auspex feature engineering and model training.